[package]
name = "itunes-library-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = { version = "1.5.0", features = ["serde"] }
serde = "1.0.189"
serde_derive = "1.0.189"
